const { getEventDemand, getWeekendMultiplier } = require("../abujaEvents");

/**
 * Computes a recommended nightly rate. The multipliers are deterministic;
 * only the human-facing explanation is generated by AI on top of this output.
 *
 * @param {object} input
 * @param {number} input.baseNightlyRate - host's set floor rate, in NGN
 * @param {string} input.date - "YYYY-MM-DD" being priced
 * @param {number} [input.occupancyLast30Days] - 0-1, recent occupancy rate
 * @param {"Maitama"|"Wuse II"|"Jabi"|string} input.location
 * @returns {{recommendedRate: number, multiplier: number, factors: object}}
 */
function calculatePrice(input) {
  const { multiplier: eventMultiplier, events } = getEventDemand(input.date);
  const weekendMultiplier = getWeekendMultiplier(input.date);

  // Low recent occupancy nudges price down slightly to stimulate bookings;
  // high occupancy nudges it up. Capped so it never swings pricing wildly.
  let occupancyMultiplier = 1;
  if (typeof input.occupancyLast30Days === "number") {
    if (input.occupancyLast30Days < 0.3) occupancyMultiplier = 0.92;
    else if (input.occupancyLast30Days > 0.85) occupancyMultiplier = 1.1;
  }

  const combinedMultiplier = round(eventMultiplier * weekendMultiplier * occupancyMultiplier);
  const recommendedRate = Math.round((input.baseNightlyRate * combinedMultiplier) / 500) * 500; // round to nearest ₦500

  return {
    recommendedRate,
    multiplier: combinedMultiplier,
    factors: {
      eventMultiplier,
      matchedEvents: events,
      weekendMultiplier,
      occupancyMultiplier,
    },
  };
}

function round(n) {
  return Math.round(n * 100) / 100;
}

module.exports = { calculatePrice };
